compile-library:
  stage: build
  script:
    - ./gradlew clean build -x test

compile-plugin:
  stage: build
  script:
    - ./plugin/gradlew clean build -x test

library-unit-tests:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - '**/build/test-results/test/TEST-*.xml'
    reports:
      junit: '**/build/test-results/test/TEST-*.xml'

publish-plugin:
  stage: deploy
  script:
    - ./plugin/gradlew publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^plugin-v[0-9-\.]+$/'
      when: on_success
    - when: never

publish-library:
  stage: deploy
  script:
    - ./gradlew publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9-\.]$/'
      when: on_success
    - when: never
